feat: add springboot component source code
serverless-components/tencent-examples pull request #58
Opened 2021-01-08 07:40 UTC by LinLzis

2021-01-08 07:54 UTC, yugasun approved these changes

2021-01-08 07:55 UTC, yugasun requested changes
Please add readme for this project demo.

2021-01-08 08:54 UTC, timqian commented
Looks this template will not be directly deployable, if so, we will also need to remove the deploy command here:
https://github.com/serverless-components/tencent-examples/blob/master/.github/workflows/springboot-starter.yml#L31

2021-01-09 08:50 UTC, LinLzis commented
> Looks this template will not be directly deployable, if so, we will also need to remove the deploy command here:
> https://github.com/serverless-components/tencent-examples/blob/master/.github/workflows/springboot-starter.yml#L31

Refs this PR to remove deploy command.
https://github.com/serverless-components/tencent-examples/pull/59

2021-01-11 02:24 UTC, yugasun approved these changes

2021-01-11 02:30 UTC, merged