Improve docs for config file in components
serverless-components/tencent-examples pull request #66
Opened 2021-02-25 10:15 UTC by zongUMR

Improve: https://github.com/serverless/roadmap-tencent/issues/775

Components:
- [ ] Next.js
- [ ] Nuxt.js
- [ ] react-starter
- [ ] Fullstack
- [ ] Eggjs
- [ ] SCF-nodejs

2021-02-26 02:27 UTC, yugasun requested changes

2021-02-26 02:27 UTC, yugasun commented on fullstack/src/frontend/serverless.yml
> +    src: ./ # 你构建的项目代码目录。
If config `hook` and  `dist`, `src` is no need.

2021-02-26 02:27 UTC, yugasun commented on react-starter/src/serverless.yml
> +    src: ./ # 你构建的项目代码目录
If config `hook` and `dist`, `src` is no need.

2021-02-26 06:28 UTC, timqian approved these changes
LGTM

2021-03-03 07:06 UTC, ole3021 commented
Update the doc with a commit

* reorder the basic info
* Update optional value list
* fix some comments

2021-03-09 07:06 UTC, ole3021 commented
* 统一注释内容和样式
* 添加引用链接
* 添加express 注释帮助
* 精简注释内容
* 移除多余注释内容

2021-03-09 08:09 UTC, zongUMR commented
>     * 统一注释内容和样式
> 
>     * 添加引用链接
> 
>     * 添加express 注释帮助
> 
>     * 精简注释内容
> 
>     * 移除多余注释内容

` express-starter/src/serverless.yml ` has conflicts on your this commit

2021-03-10 07:48 UTC, timqian commented
express-starter 的 yml 没修完全，inputs 等内容有重复 @ole3021

2021-03-15 09:46 UTC, ole3021 commented
Have checked and tested all config files.

2021-03-15 09:46 UTC, ole3021 approved these changes

2021-03-15 13:32 UTC, timqian approved these changes

2021-03-16 01:19 UTC, merged